name: Keep n8n Alive

on:
  schedule:
    - cron: '*/13 * * * *'  # Every 14 minutes
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n instance
        run: |
          curl -I https://resume-optimizer-n8n.onrender.com
          echo "Pinged at $(date)"